version: '3.4'
services:
  client:
    build:
      context: .
      target: client
  proxy:
    build:
      context: .
      target: proxy
  prometheus:
    build:
      context: .
      target: prometheus
    ports:
      - 9090:9090
