global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'kube-scheduler'
    proxy_url: http://proxy:8080/
    static_configs:
      - targets: ['kube-scheduler:10251']
  - job_name: 'kube-controller-manager'
    proxy_url: http://proxy:8080/
    static_configs:
      - targets: ['kube-controller-manager:10257']
