apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: $apiserver-namespace # needs to be changed
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: chacr.azurecr.io/pushprox_client_v2
        command: ['/app/pushprox-client', '--proxy-url=http://10.0.84.15:8080', '--fqdn=172.24.4.28', '--connect-ip=172.24.0.54', '--connect-port=10001'] # proxy url is the service, fqdn is the port of component, connect ip is apiserver port, connect port is envoy port
        ports:
        - containerPort: 1111